#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jun 03 20:05:42 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=
