#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 12 11:32:36 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=
